### ISSUE TITLE
ああああああああああああああああああああああああああああああああ:shi::shi::shi::shi::shi::abura_de_agete_agemashoune:

### ISSUE THREAD

**Issue by manmen2414** [manmen2414/study_lua_manmen2414#1]
undefined

**Comment by manmen2414** [comment]
は？

**Comment by manmen2414** [comment]
VSCodeの機能で勝手に追加されてる(((

**Comment by manmen2414** [comment]
ああああああああああああああああああああああああああああああああ:shi::shi::shi::shi::shi::abura_de_agete_agemashoune

**Comment by manmen2414** [comment]
![image](https://github.com/manmen2414/study_lua_manmen2414/assets/102225383/3d98c2d3-62ce-4889-b05f-212b6436404d)
Descripion: I made it from mistake. vscode can create issue from TODO.
## Do not make it from mistake, you.

**Comment by akki697222** [comment]
a

**Comment by akki697222** [comment]
O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A- JO-ooo-oo-oo-oo EEEEO-A-AAA-AAAA
